#!/usr/bin/env bash
# Rewrite /etc/hosts so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

tmp_file="$(mktemp)"

# Create a new version of /etc/hosts without the old localhost and facebook.com entries
awk '
  !/^[[:space:]]*127\.0\.0\.1[[:space:]]+localhost(\b.*)?$/ &&
  $0 !~ /(^|[[:space:]])facebook\.com([[:space:]]|$)/
  { print }
  END {
    print "127.0.0.2 localhost"
    print "8.8.8.8 facebook.com"
  }
' /etc/hosts > "$tmp_file"

# Replace the original /etc/hosts with the new version
cp "$tmp_file" /etc/hosts
rm -f "$tmp_file"
