#!/usr/bin/env bash
# This script modifies /etc/hosts so localhost -> 127.0.0.2 and facebook.com -> 8.8.8.8

# Remove any previous entries
sed -i '/127\.0\.0\.2 localhost/d' /etc/hosts
sed -i '/8\.8\.8\.8 facebook\.com/d' /etc/hosts
sed -i '/127\.0\.0\.1[[:space:]]\+localhost/d' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts

# Add the required ones
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
